### ISSUE TITLE
Long code lines are not wrapping on Firefox

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/highlightjs#3]
To fix the ridiculous non-wrapping of long lines and the following line put in proper class in style file fixes the issue:

```
{
  white-space: pre-wrap !important;
}

```

**Comment by indigoxela** [comment]
@alanmels I suspect, this report should go somewhere else. Either to [Highlightjs](https://github.com/highlightjs/highlight.js) or to the Backdrop theme in use. As I can see, the module has no css code on its own.

What theme are you using? I'm aware that Basis doesn't take care of `<pre>` tags, for instance.

A different approach: horizontal scrollbar on overflow.
```
pre {
  overflow-x: auto;
  max-width: 100%;
}
```

**Comment by alanmels** [comment]
Yes, I was using the Basis theme. Need to run some more tests, however as I remember without any code-highlighting modules the long lines wrap on Basis as expected.

**Comment by ghost** [comment]
@alanmels I tested this and if you just have `<code>Long text...</code>` then on Basis it wraps. If you install Highlightjs and select the `<code>` wrapping option, then it styles the code, but it still wraps.

However if your code uses `<pre><code>Long text...</code></pre>` then it doesn't wrap in Basis. And installing Highlightjs has no effect on the wrapping.

So it seems your issue is with Basis and/or how you style your code. Closing this issue.
